# Generated by Django 3.1 on 2020-09-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_auto_20200901_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='crm',
            new_name='CRM',
        ),
    ]
