# Generated by Django 3.1 on 2020-09-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_auto_20200901_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='CRM',
            new_name='crm',
        ),
    ]
