# Generated by Django 3.1 on 2020-09-01 21:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0002_auto_20200901_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=datetime.date.today)),
                ('horario', models.TimeField()),
                ('medico', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
            ],
        ),
    ]
